name: Build Windows App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # GitHub zapne stroj s Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask rembg pillow onnxruntime pywebview pyinstaller

    - name: Build with PyInstaller
      run: |
        # Používáme středník jako oddělovač dat pro Windows
        pyinstaller --noconsole --onedir --name "Bidli-Foto-Optimizer" --icon="bidli.ico" --add-data "templates;templates" --add-data "static;static" --collect-all webview --collect-all rembg app.py

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: Bidli-Windows-App
        path: dist/Bidli-Foto-Optimizer/