name: Build Apps

on:
  workflow_dispatch:  # Spustí se ručně kliknutím na tlačítko v GitHubu

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v4

      - name: Nastavení Pythonu 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instalace závislostí
        run: pip install -r requirements.txt

      - name: Sestavení EXE pomocí PyInstaller
        run: pyinstaller Bidli-Foto-App.spec --clean

      - name: Upload hotového buildu
        uses: actions/upload-artifact@v4
        with:
          name: Bidli-Foto-App-Windows
          path: dist/Bidli-Foto-App/
          retention-days: 30

  build-mac-universal:
    runs-on: macos-latest  # Apple Silicon – umí sestavit universal2 pro Intel i M-chip
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v4

      - name: Nastavení Pythonu 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Instalace závislostí
        run: pip install -r requirements.txt

      - name: Sestavení universal2 .app pomocí PyInstaller
        run: pyinstaller Bidli-Foto-App-Mac.spec --target-arch universal2 --clean

      - name: Zabalení .app do ZIP
        run: zip -r Bidli-Foto-App-Universal.zip dist/Bidli-Foto-App.app

      - name: Upload hotového buildu
        uses: actions/upload-artifact@v4
        with:
          name: Bidli-Foto-App-Mac-Universal
          path: Bidli-Foto-App-Universal.zip
          retention-days: 30
